// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsikrnwpwyfhcutllwlx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzaWtybndwd3lmaGN1dGxsd2x4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTc5OTksImV4cCI6MjA2MDgzMzk5OX0.hWiVOPASlDU2Egqt7z6edCSRDxOt8KoC_DNNMll9Bmc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);